export const TASKS_ACTIONS = {
  DELETE_TASK: "DELETE_TASK",
  ADD_TASK: "ADD_TASK",
  TOGGLE_CHECKBOX: "TOGGLE_CHECKBOX",
  FILTER_TASKS: "FILTER_TASKS",
  addDescriptionTask: "addDescriptionTask",
};

export const USER_ACTIONS = {
  USER_AUTHORIZATION: "USER_AUTHORIZATION",
};
